<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.2.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Contact Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'thank-you.html',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'rmdatasolutions.info@gmail.com',
		'to' => 'rmdatasolutions.info@gmail.com'
	),
	'fields' => array(
		'custom_U2808' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Contact Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Contact Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 3,
			'type' => 'email',
			'label' => 'Contact Phone',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Contact Phone\' is required.',
				'format' => 'Field \'Contact Phone\' has an invalid email.'
			)
		),
		'custom_U2813' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Contact  Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Contact  Email\' is required.'
			)
		),
		'custom_U2785' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Address',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Address\' is required.'
			)
		),
		'custom_U2817' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Message (Optional)',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U2914' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Brief Description of Work',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Brief Description of Work\' is required.'
			)
		)
	)
);

process_form($form);
?>
