<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.2.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Test and Tag Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'thank-you.html',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'quotes@rmdatasolutions.com.au',
		'to' => 'quotes@rmdatasolutions.com.au'
	),
	'fields' => array(
		'Email' => array(
			'order' => 5,
			'type' => 'email',
			'label' => 'Contact Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Contact Email\' is required.',
				'format' => 'Field \'Contact Email\' has an invalid email.'
			)
		),
		'custom_U3515' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Estimated Amount of Appliances to be Tested',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U3519' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Business Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Business Name\' is required.'
			)
		),
		'custom_U3588' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Contact Number',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Contact Number\' is required.'
			)
		),
		'custom_U3605' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Business Address',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Business Address\' is required.'
			)
		),
		'custom_U8151' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Contact Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Contact Name\' is required.'
			)
		)
	)
);

process_form($form);
?>
